/**
 * Rasterises a monospace ASCII atlas into a committed TypeScript module.
 *
 * Same idea as vgpu's own blue-noise table: generate once, commit the bytes, and
 * let both the browser and the headless Node preview read identical data. No
 * font loading at runtime, and the preview is guaranteed to match the site.
 *
 *   npm run build:font
 */
import { createCanvas } from "@napi-rs/canvas";
import { writeFileSync } from "node:fs";
import { PNG } from "pngjs";

const FIRST = 32;
const LAST = 126;
const COUNT = LAST - FIRST + 1; // 95 printable ASCII
const CELL_W = 18;
const CELL_H = 30;
const COLS = 16;
const ROWS = Math.ceil(COUNT / COLS); // 6
const W = CELL_W * COLS;
const H = CELL_H * ROWS;

const canvas = createCanvas(W, H);
const ctx = canvas.getContext("2d");
ctx.fillStyle = "#000";
ctx.fillRect(0, 0, W, H);
ctx.fillStyle = "#fff";
ctx.font = '24px Menlo, monospace';
ctx.textBaseline = "alphabetic";

for (let i = 0; i < COUNT; i++) {
  const ch = String.fromCharCode(FIRST + i);
  const col = i % COLS;
  const row = Math.floor(i / COLS);
  const metrics = ctx.measureText(ch);
  // Centre horizontally in the cell; sit the baseline so ascenders and
  // descenders both clear the cell edges.
  const x = col * CELL_W + (CELL_W - metrics.width) / 2;
  const y = row * CELL_H + CELL_H - 7;
  ctx.fillText(ch, x, y);
}

const rgba = ctx.getImageData(0, 0, W, H).data;
const alpha = new Uint8Array(W * H);
for (let i = 0; i < W * H; i++) alpha[i] = rgba[i * 4]; // white on black -> red channel

const base64 = Buffer.from(alpha).toString("base64");

writeFileSync(
  "src/gpu/font/atlas.ts",
  `// Generated by scripts/build-font.mjs. Do not edit.
//
// ${COUNT} printable ASCII glyphs (${FIRST}..${LAST}) rasterised from Menlo into a
// ${COLS}x${ROWS} grid of ${CELL_W}x${CELL_H} cells. One byte of coverage per texel.
//
// Cells are sized for a 2x display: the board draws 9x15 CSS pixels per cell, so
// on a retina screen that is exactly one atlas texel per device pixel, and on a
// 1x screen it minifies cleanly. Sizing the atlas for 1x instead would leave
// every retina visitor reading magnified, blurry glyphs.

export const FONT_FIRST_CHAR = ${FIRST};
export const FONT_CHAR_COUNT = ${COUNT};
export const FONT_CELL = [${CELL_W}, ${CELL_H}] as const;
export const FONT_GRID = [${COLS}, ${ROWS}] as const;
export const FONT_ATLAS_SIZE = [${W}, ${H}] as const;

const DATA =
${base64.match(/.{1,100}/g).map((line) => `  "${line}"`).join(" +\n")};

let cached: Uint8Array | undefined;

/** Single-channel coverage bytes, row-major, ${W}x${H}. */
export function fontAtlasBytes(): Uint8Array {
  if (cached) return cached;
  const binary = atob(DATA);
  const out = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) out[i] = binary.charCodeAt(i);
  cached = out;
  return out;
}
`,
);

// Visual check: write the atlas as a PNG so it can actually be looked at.
const png = new PNG({ width: W, height: H });
for (let i = 0; i < W * H; i++) {
  png.data[i * 4] = alpha[i];
  png.data[i * 4 + 1] = alpha[i];
  png.data[i * 4 + 2] = alpha[i];
  png.data[i * 4 + 3] = 255;
}
writeFileSync("preview/font-atlas.png", PNG.sync.write(png));

console.log(`atlas ${W}x${H}, ${COUNT} glyphs, ${(base64.length / 1024).toFixed(1)}KB base64`);
